kind = "web"
previewPath = "/"
title = "RCM_Client"
version = "1.0.0"
id = "artifacts/rcm"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25666

[services.development]
run = "pnpm --filter @workspace/rcm-client run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/rcm-client", "run", "build" ]
publicDir = "artifacts/RCM_Client/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25666"
BASE_PATH = "/"
